name: Adminer 

on:
  schedule:
  - cron:  '30 18 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Adminer-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Adminer
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: PHP version check
      run:  docker exec adminer_adminer_1 php -v
    - name: Localhost test
      run:  |
        bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5555)" != "200" ]]; do sleep 5; done'
    - name: Localhost test
      run:  curl -I --http2 http://localhost:5555
    - name: Destroy container and file
      run:  docker-compose down
    - name: Create ENV
      env:
        ENV_TEST: ${{ secrets.ENV_TEST }}
      run: |
        echo "$ENV_TEST" > .env.test
      shell: bash
    - name: Notify on SUCCESS
      if: ${{ SUCCESS() }}
      uses: ./.github/slack-notify
      with:
        status: SUCCESS
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Notify on FAIL
      if: ${{ failure() }}
      uses: ./.github/slack-notify
      with:
        status: SUCCESS
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    # - name: Slack Notification
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_CHANNEL: github_action_status
    #     SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
    #     SLACK_ICON: https://github.com/rtCamp.png?size=48
    #     SLACK_MESSAGE: 'Post Content Adminer AMD64 :rocket:'
    #     SLACK_TITLE: Post Title
    #     SLACK_USERNAME: rtCamp
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  Adminer-ARM64:
    runs-on: ubuntu-22.04
    name: Adminer-ARM64
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
      - name: Build the Docker image Adminer
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: PHP version check
        run:  docker exec adminer_adminer_1 php -v
      - name: Localhost test
        run:  |
          bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5555)" != "200" ]]; do sleep 5; done'
      - name: Localhost test
        run:  curl -I --http2 http://localhost:5555
      - name: Destroy container and file
        run:  docker-compose down
      - name: Create ENV 
        env:
          ENV_TEST: ${{ secrets.ENV_TEST }}
        run: |
          echo "$ENV_TEST" > .env.test
        shell: bash
      - name: Notify on SUCCESS
        if: ${{ SUCCESS() }}
        uses: ./.github/actions/slack-notify
        with:
          status: SUCCESS
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify on FAIL
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          status: SUCCESS
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      # - name: Slack Notification
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_CHANNEL: github_action_status
      #     SLACK_COLOR: ${{ job.status }}
      #     SLACK_ICON: https://github.com/rtCamp.png?size=48
      #     SLACK_MESSAGE: 'Post Content Adminer ARM64 :rocket:'
      #     SLACK_TITLE: Post Title
      #     SLACK_USERNAME: rtCamp
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
