name: Adminer 

on:
  schedule:
  - cron:  '30 18 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Adminer-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Adminer
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: PHP version check
      run:  docker exec adminer_adminer_1 php -v
    - name: Localhost test
      run:  |
        bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5555)" != "200" ]]; do sleep 5; done'
    - name: Localhost test
      run:  curl -I --http2 http://localhost:5555
    - name: Destroy container and file
      run:  docker-compose down
    - name: Create ENV
      env:
        ENV_TEST: ${{ secrets.ENV_TEST }}
      run: |
        echo "$ENV_TEST" > .env.test
      shell: bash
    - name: Notify on SUCCESS
      if: ${{ SUCCESS() }}
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C06H0SB11JL'

      # with:
      #   status: ${{ job.status }}
      #   notification_title: "{emoji} *{job}* has {status_message}"
      #   message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
      #   footer: "Linked Repo <{repo_url}|{repo}>" 
      #   mention_users: "D056LFW47NF,"
      #   mention_users_when: "SUCCESS"
      #   mention_groups: "C06H0SB11JL"
      #   mention_groups_when: "SUCCESS"
        payload: |
          {
            "text": "GitHub Action failed",
            "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Production deployment check failed* :fire_engine:\n High error rate detected after deployment! Rolling back..."
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github: Failed action"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":grafana: Resolve"
                      },
                      "url": "https://<your_organization>.grafana.net/d/my-app-dashboard?from=now-1h&to=now"
                    }
                  ]
                }
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SUCCESS }}
    - name: Notify on FAIL
      if: ${{ failure() }}
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notification_title: "{emoji} *{job}* has {status_message}"
        message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
        footer: "Linked Repo <{repo_url}|{repo}>"
        mention_users: "D056LFW47NF"
        mention_users_when: "failure,warnings"
        mention_groups: "C06G95T1YH3"
        mention_groups_when: "failure,warnings"
        payload: |
          {
            "text": "GitHub Action failed",
            "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Production deployment check failed* :fire_engine:\n High error rate detected after deployment! Rolling back..."
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github: Failed action"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":grafana: Resolve"
                      },
                      "url": "https://<your_organization>.grafana.net/d/my-app-dashboard?from=now-1h&to=now"
                    }
                  ]
                }
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FAIL }}
  Adminer-ARM64:
    runs-on: ubuntu-22.04
    name: Adminer-ARM64
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
      - name: Build the Docker image Adminer
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: PHP version check
        run:  docker exec adminer_adminer_1 php -v
      - name: Localhost test
        run:  |
          bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5555)" != "200" ]]; do sleep 5; done'
      - name: Localhost test
        run:  curl -I --http2 http://localhost:5555
      - name: Destroy container and file
        run:  docker-compose down
      - name: Create ENV
        env:
          ENV_TEST: ${{ secrets.ENV_TEST }}
        run: |
          echo "$ENV_TEST" > .env.test
        shell: bash
      - name: Notify on SUCCESS
        if: ${{ SUCCESS() }}
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "{emoji} *{job}* has {status_message}"
          message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
          footer: "Linked Repo <{repo_url}|{repo}>" 
          mention_users: "D056LFW47NF,"
          mention_users_when: "SUCCESS"
          mention_groups: "C06H0SB11JL"
          mention_groups_when: "SUCCESS"
          payload: |
            {
              "text": "GitHub Action failed",
              "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Production deployment check failed* :fire_engine:\n High error rate detected after deployment! Rolling back..."
                    }
                  },
                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": ":github: Failed action"
                        },
                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                      },
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": ":grafana: Resolve"
                        },
                        "url": "https://<your_organization>.grafana.net/d/my-app-dashboard?from=now-1h&to=now"
                      }
                    ]
                  }
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SUCCESS }}
      - name: Notify on FAIL
        if: ${{ failure() }}
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "{emoji} *{job}* has {status_message}"
          message_format: "*{workflow}* {status_message} in <{branch_url}|{branch}> Architecture <{run_url}|{job}> Approved by ${{ github.event.head_commit.author.name }}"
          footer: "Linked Repo <{repo_url}|{repo}>"
          mention_users: "D056LFW47NF"
          mention_users_when: "failure,warnings"
          mention_groups: "C06G95T1YH3"
          mention_groups_when: "failure,warnings"
          payload: |
            {
              "text": "GitHub Action failed",
              "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Production deployment check failed* :fire_engine:\n High error rate detected after deployment! Rolling back..."
                    }
                  },
                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": ":github: Failed action"
                        },
                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                      },
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": ":grafana: Resolve"
                        },
                        "url": "https://<your_organization>.grafana.net/d/my-app-dashboard?from=now-1h&to=now"
                      }
                    ]
                  }
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FAIL }}
