name: Adminer 

on:
  schedule:
  - cron:  '30 18 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  Adminer-AMD64:
    runs-on: ubuntu-latest
    env: SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Adminer
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: PHP version check
      run:  docker exec adminer_adminer_1 php -v
    - name: Localhost test
      run:  |
        bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5555)" != "200" ]]; do sleep 5; done'
    - name: Localhost test
      run:  curl -I --http2 http://localhost:5555
    - name: Destroy container and file
      run:  docker-compose down
    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        channel: '#github_action_status'
        message: Build {{ env.GITHUB_REF_NAME }} branch Successfully
      if: always()
  Adminer-ARM64:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Adminer
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: PHP version check
      run:  docker exec adminer_adminer_1 php -v
    - name: Localhost test
      run:  |
        bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5555)" != "200" ]]; do sleep 5; done'
    - name: Localhost test
      run:  curl -I --http2 http://localhost:5555
    - name: Destroy container and file
      run:  |
        docker-compose down
        echo "y" | docker system prune -a

